let suggestion = [
  "what is your name?",
  "what is your father name?",
  "WHAT DO YOU DO?",
  "what is your father income",
  "how much mark in tenth standard",
  `how much mark in 12 standard`,
  `what is current cgpa`,
  `how was about your next plan`,
  `what is css means`,
  `what is js means`,
  `what is full form html`,
  `nee yaru`,
  `un peru ena`,
  `va machane va mchane`,
  `poo vechane poo vechane`,
  `vanakam`,
  `vanthanam`,
  `bye`,
  `good nught`,
  `take care`,
  `dada`,
  `caca`,
  `thejas`,
];
